name: Go Testing
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer:
        - 1.23.x
    steps:
      - uses: actions/checkout@v4
      - name: Setup go ${{ matrix.goVer }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVer }}
      - name: Go test
        run: |
          docker compose -f ./nebula-docker-compose/docker-compose.yaml up -d
          sleep 10
          go test -v -race --tags=integration --covermode=atomic --coverprofile coverage.out
      - name: down
        if: always()
        run: |
          docker compose -f ./nebula-docker-compose/docker-compose.yaml down -v
  test-with-ssl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer:
        - 1.23.x
    steps:
      - uses: actions/checkout@v4
      - name: Setup go ${{ matrix.goVer }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVer }}
      - name: Go test with SSL
        run: |
          enable_ssl=true docker compose -f ./nebula-docker-compose/docker-compose-ssl.yaml up -d
          sleep 10
          ssl_test=true go test -v --tags=integration -run TestSslConnection
          ssl_test=true go test -v --tags=integration -run TestSslSessionPool
      - name: Test SSL connection self-signed
        run: |
          enable_ssl=true docker compose -f ./nebula-docker-compose/docker-compose-ssl.yaml up -d
          sleep 10
          self_signed=true go test -v --tags=integration -run TestSslConnection
      - name: down
        if: always()
        run: |
          docker compose -f ./nebula-docker-compose/docker-compose-ssl.yaml down -v
